global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'pve'
    static_configs:
      - targets:
        - node1.example.com   # type here Proxmox VE node1 ip address or domain name
        - node2.example.com   # type here Proxmox VE node2 ip address or domain name
        - node3.example.com   # type here Proxmox VE node3 ip address or domain name
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221
